source 'https://rubygems.org'

group :app do 
   #Server deps
   gem "unicorn"
   gem "sinatra", :require => "sinatra/base"
   
   #Authentication
   gem "warden" #auth manager
   gem "sinatra_warden" #sinatra compat layer
   
   #Storage
   gem "redis", "~> 3.0.1"
   gem "hiredis", "~> 0.4.5"
   gem "em-synchrony" #dep for redis
   
   #Templateing
   gem "haml"
end

group :test do
   #Testing gems
   gem "rspec"
   gem "guard"
   gem "capybara"
end
